[package]
name = "file-sandbox-core"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
thiserror = "1"
sha2 = "0.10"
sha1 = "0.10"
md5 = "0.7"
blake3 = "1"
regex = "1.12.2"
